//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cod3API.Models
{
    using System;
    
    public partial class GetEms_Result1
    {
        public Nullable<double> Average { get; set; }
        public Nullable<double> NinetyNinthPercentile { get; set; }
        public Nullable<double> NineteithPercentile { get; set; }
    }
}
